// Product Page to Cart Page
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";

// Product Page add Product To Cart Page on Button Click [ CART ACTIONS ]
export const PRODUCT_ADD_REQUEST = "PRODUCT_ADD_REQUEST";
export const PRODUCT_ADDED_ON_CLICK_SUCCESS = "PRODUCT_ADDED_ON_CLICK_SUCCESS";
export const PRODUCT_ADDED_ON_CLICK_FAIL = "PRODUCT_ADDED_ON_CLICK_FAIL";
export const PRODUCT_REMOVED_ON_CLICK = "PRODUCT_REMOVED_ON_CLICK";
export const PRODUCT_UPDATE_QUANTITY = "PRODUCT_UPDATE_QUANTITY";

// Product Page Manage Size and Qunatity State

export const PRODUCT_SIZE_SET = "PRODUCT_SIZE_SET";
export const PRODUCT_QTY_SET = "PRODUCT_QTY_SET";


// MainNavigation
export const GET_PRODUCT_NUMBER_CART = "GET_PRODUCT_NUMBER_CART";

// Product List
export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL  = "PRODUCT_LIST_FAIL";

// Product Details
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL  = "PRODUCT_DETAILS_FAIL";


// User Login
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

// User Signup
export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";


// GET User Details (Info)
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

// UPDATE User Details (Info)
export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

// Checkout Info
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS"; //(Cart Actions and Reducers)
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD"; //(Cart Actions and Reducers)


// Orders
export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
